apiVersion: v1
kind: Service
metadata:
  name: mailserver-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mailserver
  ports:
  - name: smtp
    port: 25
    targetPort: 25
  - name: submission
    port: 587
    targetPort: 587
  - name: imaps
    port: 993
    targetPort: 993
  type: LoadBalancer