apiVersion: v1
kind: Secret
metadata:
  name: mailserver-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc }}
  mysql-user: {{ .Values.secrets.mysqlUser | b64enc }}
  mysql-password: {{ .Values.secrets.mysqlPassword | b64enc }}
  postfixadmin-password: {{ .Values.secrets.postfixadminPassword | b64enc }}
  aws-access-key: {{ .Values.secrets.awsAccessKey | b64enc }}
  aws-secret-key: {{ .Values.secrets.awsSecretKey | b64enc }}
  aws-region: {{ .Values.aws.region | b64enc }}
  s3-bucket: {{ .Values.aws.s3Bucket | b64enc }}