apiVersion: v1
kind: Secret
metadata:
  name: mailserver-secrets
  namespace: mailserver
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M= # base64 encoded "rootpass"
  mysql-user: bWFpbHVzZXI= # base64 encoded "mailuser"
  mysql-password: bWFpbHBhc3M= # base64 encoded "mailpass"
  postfixadmin-password: YWRtaW5wYXNz # base64 encoded "adminpass"
  aws-access-key: eW91cl9hd3NfYWNjZXNzX2tleQ== # base64 encoded "your_aws_access_key"
  aws-secret-key: eW91cl9hd3Nfc2VjcmV0X2tleQ== # base64 encoded "your_aws_secret_key"
  aws-region: eW91cl9hd3NfcmVnaW9u # base64 encoded "your_aws_region"
  s3-bucket: eW91cl9zM19idWNrZXQ= # base64 encoded "your_s3_bucket"